[package]
name = "Crispy-Chess"
version = "0.1.0"
edition = "2021"

[dependencies]
cozy-chess = "0.3" 
vampirc-uci = "0.11"

[profile.release]
opt-level = 3        # أقصى سرعة للمحرك (مهم جداً لمحركات الشطرنج)
lto = true           # تحسين وقت الربط (يزيل الأكواد الميتة من المكتبة القياسية ويقلص الحجم)
codegen-units = 1    # تحسين أفضل لسرعة وحجم البرنامج
strip = true         # السحر هنا: يزيل رموز التصحيح (سيقلص الحجم من 10 ميغا إلى 1 ميغا تقريباً!)
panic = "abort"      # يزيل أكواد تتبع الأخطاء لتقليل الحجم
